assets:
  - name: regional_sales_to_s3
    group: multi_partitioned
    description: "Export sales by date and region"
    
    # Auto-materialize policy for intelligent orchestration
    auto_materialize_policy:
      type: eager
    
    partitions_def:
      type: multi
      dimensions:
        date:
          type: daily
          start_date: "2023-01-01"
        region:
          type: static
          values: ["US", "EU", "APAC"]

    source:
      type: SQLSERVER
      connection: "SQL_SOURCE"
      configs:
        # Using {{ partition_key.dimension }} syntax
        sql: "SELECT * FROM dbo.Sales WHERE SaleDate = '{{ partition_key.date }}' AND Region = '{{ partition_key.region }}'"
      
    target:
      type: S3
      connection: "S3"
      configs:
        bucket_name: "my-dagster-poc"
        # Dynamic path with dimensions
        key: "raw/regional_sales/region={{ partition_key.region }}/date={{ partition_key.date }}/sales.csv"
        object_type: CSV
      

jobs:
  - name: multi_partition_job
    description: "Orchestrates complex multi-dimensional partitioned datasets (Daily + Static Regions)."
    selection: ["regional_sales_to_s3"]
