assets:
  - name: cross_ref_test_asset
    description: "Cross-reference test asset"
    group: testing
    partitions_def: &daily_sales_partition
      type: daily
      start_date: "2025-01-01"
      hour_offset: 19
      minute_offset: 30
    source:
      type: SFTP
      connection: sftp_prod
      configs:
        path: "{{ params.source_path }}"
        # Match multiple files
        pattern: "{{ params.source_pattern }}"
    target:
      type: S3
      connection: s3_prod
      configs:
        bucket_name: "{{ params.target_bucket }}"
        # Mix of cross-config (source.path) and runtime (item.file_name)
        key: "backups{{ source.path }}/{{ source.item.file_name }}"
    checks:
      - name: audit_file_count
        type: observation_diff
        source_key: "files_scanned"
        target_key: "files_uploaded"
        threshold: 0
  - name: cross_ref_test_asset_2
    description: "Cross-reference test asset 2"
    group: testing
    partitions_def: *daily_sales_partition
    ins:
      upstream: 
        key: cross_ref_test_asset
    source:
      type: S3
      connection: s3_prod
      configs:
        bucket_name: "{{ upstream.result.bucket_name }}"
        prefix: "{{ upstream.result.prefix }}"
    target:
      type: S3
      connection: s3_prod
      configs:
        bucket_name: "my-dagster-poc"
        key: "backups/{{ source.item.object_name }}"
    checks:
      - name: audit_file_count
        type: observation_diff
        source_key: "files_scanned"
        target_key: "files_uploaded"
        threshold: 0
jobs:
  - name: cross_ref_test_job
    selection: ["cross_ref_test_asset", "cross_ref_test_asset_2"]

schedules:
  - name: daily_cross_ref_schedule
    job: cross_ref_test_job

